In [3]:
import numpy as np

## Operações

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

In [7]:
a == b

array([False,  True, False,  True])

In [8]:
a < b

array([ True, False,  True, False])

In [9]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

In [10]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [11]:
np.logical_and(a, b)

array([ True, False, False, False])

In [12]:
np.logical_not(a)

array([False,  True, False,  True])

In [13]:
np.logical_xor(a, b)

array([False,  True,  True, False])