In [2]:
import numpy as np

## Definição

In [3]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.ones([4,4], dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [5]:
np.matrix([[1,2,3], [4,5,6], [7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Multiplicando matrizes

In [6]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
a * b

array([[ 1,  4,  9],
       [16, 25, 36]])

## Produto Escalar

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[3,4,5],[5,6,7]])
a.dot(b)


array([[22, 28, 34],
       [49, 64, 79]])

In [8]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[1,2,3],[3,4,5],[5,6,7]])
a*b

matrix([[22, 28, 34],
        [49, 64, 79]])

## Definindo operações matriciais avançadas

In [9]:
change_it = np.array([1,2,3,4,5,6,7,8]) 
change_it

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
change_it.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
change_it.reshape(2,2,2) 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
change_it = change_it.reshape(2,4)
np.transpose(change_it) 

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)
np.allclose(np.dot(a,b), np.identity(2))

True

## Criando Combinações do Jeito Certo